/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStudentView {
  'completedEnrollmentsCount' : bigint,
  'profile' : StudentProfile,
}
export interface Announcement {
  'id' : string,
  'title' : string,
  'expiresAt' : [] | [Timestamp],
  'announcementType' : AnnouncementType,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'message' : string,
  'isPinned' : boolean,
}
export interface AnnouncementInput {
  'title' : string,
  'expiresAt' : [] | [Timestamp],
  'announcementType' : AnnouncementType,
  'isActive' : boolean,
  'message' : string,
  'isPinned' : boolean,
}
export type AnnouncementType = { 'warning' : null } |
  { 'info' : null } |
  { 'urgent' : null };
export interface Bookmark {
  'id' : string,
  'itemId' : string,
  'userId' : Principal,
  'createdAt' : Timestamp,
  'itemType' : ItemType,
}
export interface BookmarkInput { 'itemId' : string, 'itemType' : ItemType }
export type Category = { 'Book' : null } |
  { 'Notes' : null } |
  { 'DigitalResource' : null } |
  { 'Merchandise' : null };
export interface ConfirmPaymentInput {
  'enrollmentId' : bigint,
  'paymentId' : string,
}
export interface Coupon {
  'id' : string,
  'expiresAt' : [] | [Timestamp],
  'value' : number,
  'code' : string,
  'createdAt' : Timestamp,
  'discountType' : DiscountType,
  'usedCount' : bigint,
  'isActive' : boolean,
  'maxUses' : bigint,
}
export interface CouponInput {
  'expiresAt' : [] | [Timestamp],
  'value' : number,
  'code' : string,
  'discountType' : DiscountType,
  'isActive' : boolean,
  'maxUses' : bigint,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'isDeleted' : boolean,
  'teacherIds' : Array<bigint>,
  'subject' : Subject,
  'instructor' : string,
  'fees' : bigint,
  'createdAt' : Timestamp,
  'description' : string,
  'level' : Level,
  'imageUrl' : [] | [string],
  'price' : bigint,
}
export interface CourseInput {
  'title' : string,
  'duration' : string,
  'teacherIds' : Array<bigint>,
  'subject' : Subject,
  'description' : string,
  'level' : Level,
  'imageUrl' : [] | [string],
  'price' : bigint,
}
export type DiscountType = { 'flat' : null } |
  { 'percent' : null };
export interface Enquiry {
  'id' : bigint,
  'status' : EnquiryStatus,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
  'course' : [] | [string],
}
export interface EnquiryInput {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'course' : [] | [string],
}
export type EnquiryStatus = { 'Contacted' : null } |
  { 'Pending' : null };
export interface Enrollment {
  'id' : bigint,
  'status' : EnrollmentStatus,
  'studentId' : Principal,
  'amountPaid' : bigint,
  'refundedAt' : [] | [Timestamp],
  'purchasedAt' : Timestamp,
  'paymentId' : string,
  'courseId' : bigint,
}
export interface EnrollmentAdminView {
  'studentPrincipal' : string,
  'coursePrice' : bigint,
  'enrollment' : Enrollment,
  'courseName' : string,
}
export type EnrollmentStatus = { 'Failed' : null } |
  { 'Refunded' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Feedback {
  'id' : string,
  'studentId' : Principal,
  'createdAt' : Timestamp,
  'comment' : string,
  'rating' : bigint,
  'courseId' : string,
}
export interface FeedbackInput {
  'comment' : string,
  'rating' : bigint,
  'courseId' : string,
}
export type FileType = { 'PDF' : null } |
  { 'Image' : null };
export type GalleryCategory = { 'team' : null } |
  { 'results' : null } |
  { 'events' : null } |
  { 'classroom' : null };
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'imageUrl' : string,
  'isVisible' : boolean,
  'category' : GalleryCategory,
}
export interface GalleryImageInput {
  'title' : string,
  'description' : [] | [string],
  'imageUrl' : string,
  'isVisible' : boolean,
  'category' : GalleryCategory,
}
export type ItemType = { 'video' : null } |
  { 'course' : null } |
  { 'material' : null };
export type Level = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Class11' : null } |
  { 'Class12' : null } |
  { 'Dropper' : null } |
  { 'Intermediate' : null };
export interface MaterialInput {
  'title' : string,
  'description' : string,
  'fileSize' : [] | [string],
  'fileType' : FileType,
  'courseId' : bigint,
  'fileUrl' : string,
}
export type MaterialType = { 'PDF' : null } |
  { 'PYQ' : null } |
  { 'Notes' : null };
export interface Notification {
  'id' : string,
  'title' : string,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
}
export interface NotificationInput {
  'title' : string,
  'notificationType' : NotificationType,
  'message' : string,
  'targetUserId' : [] | [Principal],
}
export type NotificationType = { 'announcement' : null } |
  { 'enrollment' : null } |
  { 'general' : null } |
  { 'payment' : null };
export interface Product {
  'id' : bigint,
  'title' : string,
  'createdAt' : Timestamp,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export interface ProductInput {
  'title' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export interface ProfileInput {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface PurchaseCourseInput {
  'amountPaid' : bigint,
  'paymentId' : string,
  'courseId' : bigint,
}
export interface SiteSettings {
  'telegramUrl' : string,
  'heroText' : string,
  'instagramUrl' : string,
  'whatsappNumber' : string,
  'ctaText' : string,
  'contactEmail' : string,
  'youtubeUrl' : string,
  'linkedinUrl' : string,
  'contactAddress' : string,
  'heroSubtext' : string,
  'contactPhone' : string,
}
export interface StudentProfile {
  'completedTests' : Array<bigint>,
  'userId' : Principal,
  'name' : string,
  'email' : string,
  'phone' : string,
  'enrolledCourses' : Array<bigint>,
}
export interface StudyMaterial {
  'id' : bigint,
  'title' : string,
  'isDeleted' : boolean,
  'subject' : Subject,
  'description' : string,
  'fileSize' : [] | [string],
  'fileType' : FileType,
  'courseId' : bigint,
  'uploadDate' : Timestamp,
  'materialType' : MaterialType,
  'uploadedAt' : Timestamp,
  'fileKey' : string,
  'fileUrl' : string,
}
export type Subject = { 'BST' : null } |
  { 'Economics' : null } |
  { 'Accountancy' : null } |
  { 'Maths' : null } |
  { 'Commerce' : null };
export interface Teacher {
  'id' : bigint,
  'isDeleted' : boolean,
  'name' : string,
  'email' : string,
  'specialization' : string,
  'profilePhotoUrl' : [] | [string],
}
export interface TeacherInput {
  'name' : string,
  'email' : string,
  'specialization' : string,
  'profilePhotoUrl' : [] | [string],
}
export interface Testimonial {
  'id' : string,
  'marks' : string,
  'studentName' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'text' : string,
  'photoUrl' : [] | [string],
  'isVisible' : boolean,
  'rating' : bigint,
  'isVideo' : boolean,
}
export interface TestimonialInput {
  'marks' : string,
  'studentName' : string,
  'subject' : string,
  'text' : string,
  'photoUrl' : [] | [string],
  'isVisible' : boolean,
  'rating' : bigint,
  'isVideo' : boolean,
}
export type Timestamp = bigint;
export interface Video {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'order' : bigint,
  'isPreview' : boolean,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'description' : string,
  'videoUrl' : string,
  'courseId' : string,
}
export interface VideoInput {
  'title' : string,
  'thumbnailUrl' : string,
  'order' : bigint,
  'isPreview' : boolean,
  'description' : string,
  'videoUrl' : string,
  'courseId' : string,
}
export interface _SERVICE {
  'addBookmark' : ActorMethod<[BookmarkInput], Bookmark>,
  'confirmPayment' : ActorMethod<[ConfirmPaymentInput], [] | [Enrollment]>,
  'createAnnouncement' : ActorMethod<[AnnouncementInput], Announcement>,
  'createCoupon' : ActorMethod<[CouponInput], Coupon>,
  'createCourse' : ActorMethod<[CourseInput], Course>,
  'createGalleryImage' : ActorMethod<[GalleryImageInput], GalleryImage>,
  'createNotification' : ActorMethod<[NotificationInput], Array<Notification>>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'createTeacher' : ActorMethod<[TeacherInput], Teacher>,
  'createTestimonial' : ActorMethod<[TestimonialInput], Testimonial>,
  'createVideo' : ActorMethod<
    [VideoInput],
    { 'ok' : Video } |
      { 'err' : string }
  >,
  'deleteAnnouncement' : ActorMethod<[string], boolean>,
  'deleteCoupon' : ActorMethod<[string], boolean>,
  'deleteCourse' : ActorMethod<[bigint], boolean>,
  'deleteGalleryImage' : ActorMethod<[string], boolean>,
  'deleteMaterial' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteTeacher' : ActorMethod<[bigint], boolean>,
  'deleteTestimonial' : ActorMethod<[string], boolean>,
  'deleteVideo' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'enrollInCourse' : ActorMethod<[bigint], boolean>,
  'getActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAdminCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAdminCourses' : ActorMethod<[], Array<Course>>,
  'getAdminPayments' : ActorMethod<[], Array<EnrollmentAdminView>>,
  'getAdminProducts' : ActorMethod<[], Array<Product>>,
  'getAdminStudents' : ActorMethod<[], Array<AdminStudentView>>,
  'getAvailableCourses' : ActorMethod<[], Array<Course>>,
  'getCourseDetail' : ActorMethod<[bigint], [] | [Course]>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getFeedback' : ActorMethod<[], Array<Feedback>>,
  'getFeedbackByCourse' : ActorMethod<[string], Array<Feedback>>,
  'getGalleryImages' : ActorMethod<
    [[] | [GalleryCategory]],
    Array<GalleryImage>
  >,
  'getMaterialsForCourse' : ActorMethod<[bigint], Array<StudyMaterial>>,
  'getMyBookmarks' : ActorMethod<[], Array<Bookmark>>,
  'getMyEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getMyFeedback' : ActorMethod<[], Array<Feedback>>,
  'getMyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyVideosForCourse' : ActorMethod<
    [string],
    { 'ok' : Array<Video> } |
      { 'err' : string }
  >,
  'getPreviewVideos' : ActorMethod<[], Array<Video>>,
  'getProductDetail' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getTeacher' : ActorMethod<[bigint], [] | [Teacher]>,
  'getTeachers' : ActorMethod<[], Array<Teacher>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'getVideosByCourse' : ActorMethod<[string], Array<Video>>,
  'isEnrolled' : ActorMethod<[bigint], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], bigint>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'purchaseCourse' : ActorMethod<[PurchaseCourseInput], Enrollment>,
  'removeBookmark' : ActorMethod<[string], boolean>,
  'submitEnquiry' : ActorMethod<[EnquiryInput], bigint>,
  'submitFeedback' : ActorMethod<[FeedbackInput], Feedback>,
  'toggleAnnouncementActive' : ActorMethod<[string], [] | [Announcement]>,
  'toggleGalleryImageVisibility' : ActorMethod<[string], [] | [GalleryImage]>,
  'toggleTestimonialVisibility' : ActorMethod<[string], [] | [Testimonial]>,
  'updateAnnouncement' : ActorMethod<
    [string, AnnouncementInput],
    [] | [Announcement]
  >,
  'updateCoupon' : ActorMethod<[string, CouponInput], [] | [Coupon]>,
  'updateCourse' : ActorMethod<[bigint, CourseInput], [] | [Course]>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], [] | [Product]>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], SiteSettings>,
  'updateStudentProfile' : ActorMethod<[ProfileInput], undefined>,
  'updateTeacher' : ActorMethod<[bigint, TeacherInput], [] | [Teacher]>,
  'updateTestimonial' : ActorMethod<
    [string, TestimonialInput],
    [] | [Testimonial]
  >,
  'uploadMaterial' : ActorMethod<[MaterialInput], StudyMaterial>,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];