/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemType = IDL.Variant({
  'video' : IDL.Null,
  'course' : IDL.Null,
  'material' : IDL.Null,
});
export const BookmarkInput = IDL.Record({
  'itemId' : IDL.Text,
  'itemType' : ItemType,
});
export const Timestamp = IDL.Int;
export const Bookmark = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Timestamp,
  'itemType' : ItemType,
});
export const ConfirmPaymentInput = IDL.Record({
  'enrollmentId' : IDL.Nat,
  'paymentId' : IDL.Text,
});
export const EnrollmentStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Refunded' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Enrollment = IDL.Record({
  'id' : IDL.Nat,
  'status' : EnrollmentStatus,
  'studentId' : IDL.Principal,
  'amountPaid' : IDL.Nat,
  'refundedAt' : IDL.Opt(Timestamp),
  'purchasedAt' : Timestamp,
  'paymentId' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const AnnouncementType = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'urgent' : IDL.Null,
});
export const AnnouncementInput = IDL.Record({
  'title' : IDL.Text,
  'expiresAt' : IDL.Opt(Timestamp),
  'announcementType' : AnnouncementType,
  'isActive' : IDL.Bool,
  'message' : IDL.Text,
  'isPinned' : IDL.Bool,
});
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'expiresAt' : IDL.Opt(Timestamp),
  'announcementType' : AnnouncementType,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'message' : IDL.Text,
  'isPinned' : IDL.Bool,
});
export const DiscountType = IDL.Variant({
  'flat' : IDL.Null,
  'percent' : IDL.Null,
});
export const CouponInput = IDL.Record({
  'expiresAt' : IDL.Opt(Timestamp),
  'value' : IDL.Float64,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Nat,
});
export const Coupon = IDL.Record({
  'id' : IDL.Text,
  'expiresAt' : IDL.Opt(Timestamp),
  'value' : IDL.Float64,
  'code' : IDL.Text,
  'createdAt' : Timestamp,
  'discountType' : DiscountType,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Nat,
});
export const Subject = IDL.Variant({
  'BST' : IDL.Null,
  'Economics' : IDL.Null,
  'Accountancy' : IDL.Null,
  'Maths' : IDL.Null,
  'Commerce' : IDL.Null,
});
export const Level = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Class11' : IDL.Null,
  'Class12' : IDL.Null,
  'Dropper' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const CourseInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'teacherIds' : IDL.Vec(IDL.Nat),
  'subject' : Subject,
  'description' : IDL.Text,
  'level' : Level,
  'imageUrl' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'teacherIds' : IDL.Vec(IDL.Nat),
  'subject' : Subject,
  'instructor' : IDL.Text,
  'fees' : IDL.Nat,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'level' : Level,
  'imageUrl' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const DownloadCategory = IDL.Variant({
  'admit_card' : IDL.Null,
  'study_notes' : IDL.Null,
  'certificate' : IDL.Null,
  'hall_ticket' : IDL.Null,
});
export const DownloadItemInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'fileSize' : IDL.Text,
  'category' : DownloadCategory,
  'isPublic' : IDL.Bool,
  'batchYear' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const DownloadItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'fileSize' : IDL.Text,
  'category' : DownloadCategory,
  'downloadCount' : IDL.Nat,
  'isPublic' : IDL.Bool,
  'batchYear' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const EventInput = IDL.Record({
  'status' : EventStatus,
  'title' : IDL.Text,
  'endDate' : Timestamp,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
  'isVisible' : IDL.Bool,
  'capacity' : IDL.Nat,
  'speaker' : IDL.Text,
  'eventDate' : Timestamp,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'title' : IDL.Text,
  'endDate' : Timestamp,
  'registeredCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
  'isVisible' : IDL.Bool,
  'capacity' : IDL.Nat,
  'speaker' : IDL.Text,
  'eventDate' : Timestamp,
});
export const GalleryCategory = IDL.Variant({
  'team' : IDL.Null,
  'results' : IDL.Null,
  'events' : IDL.Null,
  'classroom' : IDL.Null,
});
export const GalleryImageInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'category' : GalleryCategory,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'isVisible' : IDL.Bool,
  'category' : GalleryCategory,
});
export const NotificationType = IDL.Variant({
  'announcement' : IDL.Null,
  'enrollment' : IDL.Null,
  'general' : IDL.Null,
  'payment' : IDL.Null,
});
export const NotificationInput = IDL.Record({
  'title' : IDL.Text,
  'notificationType' : NotificationType,
  'message' : IDL.Text,
  'targetUserId' : IDL.Opt(IDL.Principal),
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Category = IDL.Variant({
  'Book' : IDL.Null,
  'Notes' : IDL.Null,
  'DigitalResource' : IDL.Null,
  'Merchandise' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'title' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const QuestionType = IDL.Variant({
  'multiple_choice' : IDL.Null,
  'essay' : IDL.Null,
});
export const QuestionInput = IDL.Record({
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'testId' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
  'orderIndex' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'explanation' : IDL.Text,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'testId' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
  'orderIndex' : IDL.Nat,
  'points' : IDL.Nat,
});
export const TeacherInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'specialization' : IDL.Text,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
});
export const Teacher = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'specialization' : IDL.Text,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
});
export const TestimonialInput = IDL.Record({
  'marks' : IDL.Text,
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'text' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
  'isVideo' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'marks' : IDL.Text,
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'isVisible' : IDL.Bool,
  'rating' : IDL.Nat,
  'isVideo' : IDL.Bool,
});
export const VideoInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'order' : IDL.Nat,
  'isPreview' : IDL.Bool,
  'description' : IDL.Text,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'order' : IDL.Nat,
  'isPreview' : IDL.Bool,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Text,
});
export const EnrollmentAdminView = IDL.Record({
  'studentPrincipal' : IDL.Text,
  'coursePrice' : IDL.Nat,
  'enrollment' : Enrollment,
  'courseName' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'completedTests' : IDL.Vec(IDL.Nat),
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'enrolledCourses' : IDL.Vec(IDL.Nat),
});
export const AdminStudentView = IDL.Record({
  'completedEnrollmentsCount' : IDL.Nat,
  'profile' : StudentProfile,
});
export const TestAnalytics = IDL.Record({
  'avgScore' : IDL.Float64,
  'passRate' : IDL.Float64,
  'totalAttempts' : IDL.Nat,
});
export const TestAttemptAnswer = IDL.Record({
  'id' : IDL.Nat,
  'pointsAwarded' : IDL.Nat,
  'attemptId' : IDL.Nat,
  'studentAnswer' : IDL.Text,
  'isCorrect' : IDL.Bool,
  'questionId' : IDL.Nat,
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
  'sessionId' : IDL.Text,
});
export const EnquiryStatus = IDL.Variant({
  'Contacted' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : EnquiryStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'course' : IDL.Opt(IDL.Text),
});
export const EventRegistration = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : Timestamp,
});
export const Feedback = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Principal,
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'courseId' : IDL.Text,
});
export const FileType = IDL.Variant({ 'PDF' : IDL.Null, 'Image' : IDL.Null });
export const MaterialType = IDL.Variant({
  'PDF' : IDL.Null,
  'PYQ' : IDL.Null,
  'Notes' : IDL.Null,
});
export const StudyMaterial = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isDeleted' : IDL.Bool,
  'subject' : Subject,
  'description' : IDL.Text,
  'fileSize' : IDL.Opt(IDL.Text),
  'fileType' : FileType,
  'courseId' : IDL.Nat,
  'uploadDate' : Timestamp,
  'materialType' : MaterialType,
  'uploadedAt' : Timestamp,
  'fileKey' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const AttemptStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'in_progress' : IDL.Null,
  'timed_out' : IDL.Null,
});
export const TestAttempt = IDL.Record({
  'id' : IDL.Nat,
  'status' : AttemptStatus,
  'startedAt' : Timestamp,
  'studentId' : IDL.Text,
  'submittedAt' : IDL.Opt(Timestamp),
  'testId' : IDL.Nat,
});
export const TestResult = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'attemptId' : IDL.Nat,
  'maxPoints' : IDL.Nat,
  'createdAt' : Timestamp,
  'grade' : IDL.Text,
  'totalPoints' : IDL.Nat,
  'timeTaken' : IDL.Int,
  'testId' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const SiteSettings = IDL.Record({
  'telegramUrl' : IDL.Text,
  'heroText' : IDL.Text,
  'instagramUrl' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'ctaText' : IDL.Text,
  'contactEmail' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'linkedinUrl' : IDL.Text,
  'contactAddress' : IDL.Text,
  'heroSubtext' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const PurchaseCourseInput = IDL.Record({
  'amountPaid' : IDL.Nat,
  'paymentId' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const EventRegistrationInput = IDL.Record({
  'eventId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const EnquiryInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'course' : IDL.Opt(IDL.Text),
});
export const FeedbackInput = IDL.Record({
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'courseId' : IDL.Text,
});
export const ProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const MaterialInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileSize' : IDL.Opt(IDL.Text),
  'fileType' : FileType,
  'courseId' : IDL.Nat,
  'fileUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBookmark' : IDL.Func([BookmarkInput], [Bookmark], []),
  'clearChatSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'confirmPayment' : IDL.Func([ConfirmPaymentInput], [IDL.Opt(Enrollment)], []),
  'createAnnouncement' : IDL.Func([AnnouncementInput], [Announcement], []),
  'createCoupon' : IDL.Func([CouponInput], [Coupon], []),
  'createCourse' : IDL.Func([CourseInput], [Course], []),
  'createDownloadItem' : IDL.Func([DownloadItemInput], [DownloadItem], []),
  'createEvent' : IDL.Func([EventInput], [Event], []),
  'createGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImage], []),
  'createNotification' : IDL.Func(
      [NotificationInput],
      [IDL.Vec(Notification)],
      [],
    ),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'createQuestion' : IDL.Func([QuestionInput], [Question], []),
  'createTeacher' : IDL.Func([TeacherInput], [Teacher], []),
  'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
  'createVideo' : IDL.Func(
      [VideoInput],
      [IDL.Variant({ 'ok' : Video, 'err' : IDL.Text })],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDownloadItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMaterial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTeacher' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteVideo' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'enrollInCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAdminCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAdminCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAdminPayments' : IDL.Func([], [IDL.Vec(EnrollmentAdminView)], ['query']),
  'getAdminProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAdminStudents' : IDL.Func([], [IDL.Vec(AdminStudentView)], ['query']),
  'getAdminTestAnalytics' : IDL.Func([IDL.Nat], [TestAnalytics], ['query']),
  'getAttemptAnswers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TestAttemptAnswer)],
      ['query'],
    ),
  'getAvailableCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getCourseDetail' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getDownloadItems' : IDL.Func(
      [IDL.Opt(DownloadCategory)],
      [IDL.Vec(DownloadItem)],
      ['query'],
    ),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getEventDetail' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
  'getEventRegistrations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EventRegistration)],
      ['query'],
    ),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getFeedbackByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Feedback)], ['query']),
  'getGalleryImages' : IDL.Func(
      [IDL.Opt(GalleryCategory)],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getMaterialsForCourse' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StudyMaterial)],
      ['query'],
    ),
  'getMyAttempts' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(TestAttempt)],
      ['query'],
    ),
  'getMyBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getMyDownloads' : IDL.Func(
      [IDL.Opt(DownloadCategory)],
      [IDL.Vec(DownloadItem)],
      ['query'],
    ),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getMyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyRegistrations' : IDL.Func([], [IDL.Vec(EventRegistration)], ['query']),
  'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getMyVideosForCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Video), 'err' : IDL.Text })],
      ['query'],
    ),
  'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPreviewVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getProductDetail' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getQuestionCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getQuestionsByTest' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getTeacher' : IDL.Func([IDL.Nat], [IDL.Opt(Teacher)], ['query']),
  'getTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getTestLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getVideosByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'incrementDownloadCount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'isEnrolled' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'purchaseCourse' : IDL.Func([PurchaseCourseInput], [Enrollment], []),
  'registerForEvent' : IDL.Func(
      [EventRegistrationInput],
      [EventRegistration],
      [],
    ),
  'removeBookmark' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'startAttempt' : IDL.Func([IDL.Nat], [TestAttempt], []),
  'submitAttempt' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      [TestResult],
      [],
    ),
  'submitEnquiry' : IDL.Func([EnquiryInput], [IDL.Nat], []),
  'submitFeedback' : IDL.Func([FeedbackInput], [Feedback], []),
  'toggleAnnouncementActive' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Announcement)],
      [],
    ),
  'toggleGalleryImageVisibility' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GalleryImage)],
      [],
    ),
  'toggleTestimonialVisibility' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Testimonial)],
      [],
    ),
  'updateAnnouncement' : IDL.Func(
      [IDL.Text, AnnouncementInput],
      [IDL.Opt(Announcement)],
      [],
    ),
  'updateCoupon' : IDL.Func([IDL.Text, CouponInput], [IDL.Opt(Coupon)], []),
  'updateCourse' : IDL.Func([IDL.Nat, CourseInput], [IDL.Opt(Course)], []),
  'updateDownloadItem' : IDL.Func(
      [IDL.Nat, DownloadItemInput],
      [IDL.Opt(DownloadItem)],
      [],
    ),
  'updateEvent' : IDL.Func([IDL.Nat, EventInput], [IDL.Opt(Event)], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Opt(Product)], []),
  'updateQuestion' : IDL.Func(
      [IDL.Nat, QuestionInput],
      [IDL.Opt(Question)],
      [],
    ),
  'updateSiteSettings' : IDL.Func([SiteSettings], [SiteSettings], []),
  'updateStudentProfile' : IDL.Func([ProfileInput], [], []),
  'updateTeacher' : IDL.Func([IDL.Nat, TeacherInput], [IDL.Opt(Teacher)], []),
  'updateTestimonial' : IDL.Func(
      [IDL.Text, TestimonialInput],
      [IDL.Opt(Testimonial)],
      [],
    ),
  'uploadMaterial' : IDL.Func([MaterialInput], [StudyMaterial], []),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemType = IDL.Variant({
    'video' : IDL.Null,
    'course' : IDL.Null,
    'material' : IDL.Null,
  });
  const BookmarkInput = IDL.Record({
    'itemId' : IDL.Text,
    'itemType' : ItemType,
  });
  const Timestamp = IDL.Int;
  const Bookmark = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Timestamp,
    'itemType' : ItemType,
  });
  const ConfirmPaymentInput = IDL.Record({
    'enrollmentId' : IDL.Nat,
    'paymentId' : IDL.Text,
  });
  const EnrollmentStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Enrollment = IDL.Record({
    'id' : IDL.Nat,
    'status' : EnrollmentStatus,
    'studentId' : IDL.Principal,
    'amountPaid' : IDL.Nat,
    'refundedAt' : IDL.Opt(Timestamp),
    'purchasedAt' : Timestamp,
    'paymentId' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const AnnouncementType = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const AnnouncementInput = IDL.Record({
    'title' : IDL.Text,
    'expiresAt' : IDL.Opt(Timestamp),
    'announcementType' : AnnouncementType,
    'isActive' : IDL.Bool,
    'message' : IDL.Text,
    'isPinned' : IDL.Bool,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'expiresAt' : IDL.Opt(Timestamp),
    'announcementType' : AnnouncementType,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'message' : IDL.Text,
    'isPinned' : IDL.Bool,
  });
  const DiscountType = IDL.Variant({ 'flat' : IDL.Null, 'percent' : IDL.Null });
  const CouponInput = IDL.Record({
    'expiresAt' : IDL.Opt(Timestamp),
    'value' : IDL.Float64,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Nat,
  });
  const Coupon = IDL.Record({
    'id' : IDL.Text,
    'expiresAt' : IDL.Opt(Timestamp),
    'value' : IDL.Float64,
    'code' : IDL.Text,
    'createdAt' : Timestamp,
    'discountType' : DiscountType,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Nat,
  });
  const Subject = IDL.Variant({
    'BST' : IDL.Null,
    'Economics' : IDL.Null,
    'Accountancy' : IDL.Null,
    'Maths' : IDL.Null,
    'Commerce' : IDL.Null,
  });
  const Level = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Class11' : IDL.Null,
    'Class12' : IDL.Null,
    'Dropper' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const CourseInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'teacherIds' : IDL.Vec(IDL.Nat),
    'subject' : Subject,
    'description' : IDL.Text,
    'level' : Level,
    'imageUrl' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'teacherIds' : IDL.Vec(IDL.Nat),
    'subject' : Subject,
    'instructor' : IDL.Text,
    'fees' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'level' : Level,
    'imageUrl' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const DownloadCategory = IDL.Variant({
    'admit_card' : IDL.Null,
    'study_notes' : IDL.Null,
    'certificate' : IDL.Null,
    'hall_ticket' : IDL.Null,
  });
  const DownloadItemInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'fileSize' : IDL.Text,
    'category' : DownloadCategory,
    'isPublic' : IDL.Bool,
    'batchYear' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const DownloadItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'fileSize' : IDL.Text,
    'category' : DownloadCategory,
    'downloadCount' : IDL.Nat,
    'isPublic' : IDL.Bool,
    'batchYear' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const EventStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const EventInput = IDL.Record({
    'status' : EventStatus,
    'title' : IDL.Text,
    'endDate' : Timestamp,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
    'isVisible' : IDL.Bool,
    'capacity' : IDL.Nat,
    'speaker' : IDL.Text,
    'eventDate' : Timestamp,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'title' : IDL.Text,
    'endDate' : Timestamp,
    'registeredCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
    'isVisible' : IDL.Bool,
    'capacity' : IDL.Nat,
    'speaker' : IDL.Text,
    'eventDate' : Timestamp,
  });
  const GalleryCategory = IDL.Variant({
    'team' : IDL.Null,
    'results' : IDL.Null,
    'events' : IDL.Null,
    'classroom' : IDL.Null,
  });
  const GalleryImageInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'category' : GalleryCategory,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'isVisible' : IDL.Bool,
    'category' : GalleryCategory,
  });
  const NotificationType = IDL.Variant({
    'announcement' : IDL.Null,
    'enrollment' : IDL.Null,
    'general' : IDL.Null,
    'payment' : IDL.Null,
  });
  const NotificationInput = IDL.Record({
    'title' : IDL.Text,
    'notificationType' : NotificationType,
    'message' : IDL.Text,
    'targetUserId' : IDL.Opt(IDL.Principal),
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Category = IDL.Variant({
    'Book' : IDL.Null,
    'Notes' : IDL.Null,
    'DigitalResource' : IDL.Null,
    'Merchandise' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'title' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const QuestionType = IDL.Variant({
    'multiple_choice' : IDL.Null,
    'essay' : IDL.Null,
  });
  const QuestionInput = IDL.Record({
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'testId' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
    'orderIndex' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'explanation' : IDL.Text,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'testId' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
    'orderIndex' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const TeacherInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'specialization' : IDL.Text,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
  });
  const Teacher = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'specialization' : IDL.Text,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
  });
  const TestimonialInput = IDL.Record({
    'marks' : IDL.Text,
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'text' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
    'isVideo' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'marks' : IDL.Text,
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'isVisible' : IDL.Bool,
    'rating' : IDL.Nat,
    'isVideo' : IDL.Bool,
  });
  const VideoInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'order' : IDL.Nat,
    'isPreview' : IDL.Bool,
    'description' : IDL.Text,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'order' : IDL.Nat,
    'isPreview' : IDL.Bool,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const EnrollmentAdminView = IDL.Record({
    'studentPrincipal' : IDL.Text,
    'coursePrice' : IDL.Nat,
    'enrollment' : Enrollment,
    'courseName' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'completedTests' : IDL.Vec(IDL.Nat),
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'enrolledCourses' : IDL.Vec(IDL.Nat),
  });
  const AdminStudentView = IDL.Record({
    'completedEnrollmentsCount' : IDL.Nat,
    'profile' : StudentProfile,
  });
  const TestAnalytics = IDL.Record({
    'avgScore' : IDL.Float64,
    'passRate' : IDL.Float64,
    'totalAttempts' : IDL.Nat,
  });
  const TestAttemptAnswer = IDL.Record({
    'id' : IDL.Nat,
    'pointsAwarded' : IDL.Nat,
    'attemptId' : IDL.Nat,
    'studentAnswer' : IDL.Text,
    'isCorrect' : IDL.Bool,
    'questionId' : IDL.Nat,
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
    'sessionId' : IDL.Text,
  });
  const EnquiryStatus = IDL.Variant({
    'Contacted' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : EnquiryStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'course' : IDL.Opt(IDL.Text),
  });
  const EventRegistration = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : Timestamp,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Principal,
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'courseId' : IDL.Text,
  });
  const FileType = IDL.Variant({ 'PDF' : IDL.Null, 'Image' : IDL.Null });
  const MaterialType = IDL.Variant({
    'PDF' : IDL.Null,
    'PYQ' : IDL.Null,
    'Notes' : IDL.Null,
  });
  const StudyMaterial = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isDeleted' : IDL.Bool,
    'subject' : Subject,
    'description' : IDL.Text,
    'fileSize' : IDL.Opt(IDL.Text),
    'fileType' : FileType,
    'courseId' : IDL.Nat,
    'uploadDate' : Timestamp,
    'materialType' : MaterialType,
    'uploadedAt' : Timestamp,
    'fileKey' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const AttemptStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'in_progress' : IDL.Null,
    'timed_out' : IDL.Null,
  });
  const TestAttempt = IDL.Record({
    'id' : IDL.Nat,
    'status' : AttemptStatus,
    'startedAt' : Timestamp,
    'studentId' : IDL.Text,
    'submittedAt' : IDL.Opt(Timestamp),
    'testId' : IDL.Nat,
  });
  const TestResult = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'attemptId' : IDL.Nat,
    'maxPoints' : IDL.Nat,
    'createdAt' : Timestamp,
    'grade' : IDL.Text,
    'totalPoints' : IDL.Nat,
    'timeTaken' : IDL.Int,
    'testId' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const SiteSettings = IDL.Record({
    'telegramUrl' : IDL.Text,
    'heroText' : IDL.Text,
    'instagramUrl' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'ctaText' : IDL.Text,
    'contactEmail' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'linkedinUrl' : IDL.Text,
    'contactAddress' : IDL.Text,
    'heroSubtext' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const PurchaseCourseInput = IDL.Record({
    'amountPaid' : IDL.Nat,
    'paymentId' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const EventRegistrationInput = IDL.Record({
    'eventId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const EnquiryInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'course' : IDL.Opt(IDL.Text),
  });
  const FeedbackInput = IDL.Record({
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'courseId' : IDL.Text,
  });
  const ProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MaterialInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileSize' : IDL.Opt(IDL.Text),
    'fileType' : FileType,
    'courseId' : IDL.Nat,
    'fileUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addBookmark' : IDL.Func([BookmarkInput], [Bookmark], []),
    'clearChatSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'confirmPayment' : IDL.Func(
        [ConfirmPaymentInput],
        [IDL.Opt(Enrollment)],
        [],
      ),
    'createAnnouncement' : IDL.Func([AnnouncementInput], [Announcement], []),
    'createCoupon' : IDL.Func([CouponInput], [Coupon], []),
    'createCourse' : IDL.Func([CourseInput], [Course], []),
    'createDownloadItem' : IDL.Func([DownloadItemInput], [DownloadItem], []),
    'createEvent' : IDL.Func([EventInput], [Event], []),
    'createGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImage], []),
    'createNotification' : IDL.Func(
        [NotificationInput],
        [IDL.Vec(Notification)],
        [],
      ),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'createQuestion' : IDL.Func([QuestionInput], [Question], []),
    'createTeacher' : IDL.Func([TeacherInput], [Teacher], []),
    'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
    'createVideo' : IDL.Func(
        [VideoInput],
        [IDL.Variant({ 'ok' : Video, 'err' : IDL.Text })],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDownloadItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMaterial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTeacher' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteVideo' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'enrollInCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAdminCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAdminCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAdminPayments' : IDL.Func(
        [],
        [IDL.Vec(EnrollmentAdminView)],
        ['query'],
      ),
    'getAdminProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAdminStudents' : IDL.Func([], [IDL.Vec(AdminStudentView)], ['query']),
    'getAdminTestAnalytics' : IDL.Func([IDL.Nat], [TestAnalytics], ['query']),
    'getAttemptAnswers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TestAttemptAnswer)],
        ['query'],
      ),
    'getAvailableCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getCourseDetail' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getDownloadItems' : IDL.Func(
        [IDL.Opt(DownloadCategory)],
        [IDL.Vec(DownloadItem)],
        ['query'],
      ),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getEventDetail' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
    'getEventRegistrations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EventRegistration)],
        ['query'],
      ),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getFeedbackByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getGalleryImages' : IDL.Func(
        [IDL.Opt(GalleryCategory)],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getMaterialsForCourse' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudyMaterial)],
        ['query'],
      ),
    'getMyAttempts' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(TestAttempt)],
        ['query'],
      ),
    'getMyBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getMyDownloads' : IDL.Func(
        [IDL.Opt(DownloadCategory)],
        [IDL.Vec(DownloadItem)],
        ['query'],
      ),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getMyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyRegistrations' : IDL.Func(
        [],
        [IDL.Vec(EventRegistration)],
        ['query'],
      ),
    'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getMyVideosForCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Video), 'err' : IDL.Text })],
        ['query'],
      ),
    'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPreviewVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getProductDetail' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getQuestionCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getQuestionsByTest' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getTeacher' : IDL.Func([IDL.Nat], [IDL.Opt(Teacher)], ['query']),
    'getTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getTestLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getVideosByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'incrementDownloadCount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'isEnrolled' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'purchaseCourse' : IDL.Func([PurchaseCourseInput], [Enrollment], []),
    'registerForEvent' : IDL.Func(
        [EventRegistrationInput],
        [EventRegistration],
        [],
      ),
    'removeBookmark' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'startAttempt' : IDL.Func([IDL.Nat], [TestAttempt], []),
    'submitAttempt' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        [TestResult],
        [],
      ),
    'submitEnquiry' : IDL.Func([EnquiryInput], [IDL.Nat], []),
    'submitFeedback' : IDL.Func([FeedbackInput], [Feedback], []),
    'toggleAnnouncementActive' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Announcement)],
        [],
      ),
    'toggleGalleryImageVisibility' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GalleryImage)],
        [],
      ),
    'toggleTestimonialVisibility' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Testimonial)],
        [],
      ),
    'updateAnnouncement' : IDL.Func(
        [IDL.Text, AnnouncementInput],
        [IDL.Opt(Announcement)],
        [],
      ),
    'updateCoupon' : IDL.Func([IDL.Text, CouponInput], [IDL.Opt(Coupon)], []),
    'updateCourse' : IDL.Func([IDL.Nat, CourseInput], [IDL.Opt(Course)], []),
    'updateDownloadItem' : IDL.Func(
        [IDL.Nat, DownloadItemInput],
        [IDL.Opt(DownloadItem)],
        [],
      ),
    'updateEvent' : IDL.Func([IDL.Nat, EventInput], [IDL.Opt(Event)], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Opt(Product)], []),
    'updateQuestion' : IDL.Func(
        [IDL.Nat, QuestionInput],
        [IDL.Opt(Question)],
        [],
      ),
    'updateSiteSettings' : IDL.Func([SiteSettings], [SiteSettings], []),
    'updateStudentProfile' : IDL.Func([ProfileInput], [], []),
    'updateTeacher' : IDL.Func([IDL.Nat, TeacherInput], [IDL.Opt(Teacher)], []),
    'updateTestimonial' : IDL.Func(
        [IDL.Text, TestimonialInput],
        [IDL.Opt(Testimonial)],
        [],
      ),
    'uploadMaterial' : IDL.Func([MaterialInput], [StudyMaterial], []),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };